version: '3.8'

services:
  app:
    build:
      context: .  # This tells Docker Compose to build the image from the Dockerfile in the current directory
    image: mohamedelhamzi203/locationcar  # Tag the image
    ports:
      - "80:80"  # Expose the app on port 80
    networks:
      - app-network
    depends_on:
      - db  # Ensure the MySQL service is started before the app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db  # Connect phpMyAdmin to the db service
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    networks:
      - app-network
    depends_on:
      - db  # Ensure MySQL is available before starting phpMyAdmin

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
